# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14rwONiKgyv84JQXPBrUGDhKegQlSKjRk
"""

from bs4 import BeautifulSoup
import requests
from wordcloud import WordCloud
import matplotlib.pyplot as plt

print("Ingrese el link")

url = "https://es.stackoverflow.com/users/54039/triby?tab=tags"

page = requests.get(url)

soup = BeautifulSoup(page.content, 'html.parser')

eq = soup.find_all("td")

lista = list()
completelist = list()
netiquetas = list()
for i in eq:
    lista.append(i.find("a", class_="post-tag").text)

for i in eq:
    netiquetas.append(i.find("div", class_="answer-votes").text)

for j in range(len(lista)):
    print(lista[j])
    for k in range(int(netiquetas[j])):
        completelist.append(lista[j])

print(completelist)
print(lista)

wc = WordCloud(background_color="white",collocations=False).generate(' '.join(completelist))

plt.imshow(wc)
plt.axis('off')
plt.show()

from wordcloud import WordCloud
import matplotlib.pyplot as plt

text = "keys coding competetive development Python webscraping automation getsetpython projects cool awesome blockchain data machinelearning  regex loops datascience opencv ML list dictionary analysis sentiment variable set counter enumerate try except if-else for function class object instance GUI encryption security"

cloud = WordCloud(background_color="white").generate(text)

plt.imshow(cloud)
plt.axis('off')
plt.show()